/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaterialEditRouteRouteImport } from './routes/material-edit/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaterialEditIndexRouteImport } from './routes/material-edit/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'

const MaterialEditRouteRoute = MaterialEditRouteRouteImport.update({
  id: '/material-edit',
  path: '/material-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialEditIndexRoute = MaterialEditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaterialEditRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/material-edit': typeof MaterialEditRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/material-edit/': typeof MaterialEditIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/material-edit': typeof MaterialEditIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/material-edit': typeof MaterialEditRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/material-edit/': typeof MaterialEditIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/material-edit'
    | '/api/$'
    | '/material-edit/'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/$' | '/material-edit' | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/material-edit'
    | '/api/$'
    | '/material-edit/'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaterialEditRouteRoute: typeof MaterialEditRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/material-edit': {
      id: '/material-edit'
      path: '/material-edit'
      fullPath: '/material-edit'
      preLoaderRoute: typeof MaterialEditRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-edit/': {
      id: '/material-edit/'
      path: '/'
      fullPath: '/material-edit/'
      preLoaderRoute: typeof MaterialEditIndexRouteImport
      parentRoute: typeof MaterialEditRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MaterialEditRouteRouteChildren {
  MaterialEditIndexRoute: typeof MaterialEditIndexRoute
}

const MaterialEditRouteRouteChildren: MaterialEditRouteRouteChildren = {
  MaterialEditIndexRoute: MaterialEditIndexRoute,
}

const MaterialEditRouteRouteWithChildren =
  MaterialEditRouteRoute._addFileChildren(MaterialEditRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaterialEditRouteRoute: MaterialEditRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
