/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as LayoutUp_baiduIndexRouteImport } from './routes/_layout.up_baidu/index'
import { Route as LayoutMafIndexRouteImport } from './routes/_layout.maf/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUp_baiduIndexRoute = LayoutUp_baiduIndexRouteImport.update({
  id: '/up_baidu/',
  path: '/up_baidu/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutMafIndexRoute = LayoutMafIndexRouteImport.update({
  id: '/maf/',
  path: '/maf/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/api/$': typeof ApiSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/maf/': typeof LayoutMafIndexRoute
  '/up_baidu/': typeof LayoutUp_baiduIndexRoute
}
export interface FileRoutesByTo {
  '/api/$': typeof ApiSplatRoute
  '/': typeof LayoutIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/maf': typeof LayoutMafIndexRoute
  '/up_baidu': typeof LayoutUp_baiduIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_layout/': typeof LayoutIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_layout/maf/': typeof LayoutMafIndexRoute
  '/_layout/up_baidu/': typeof LayoutUp_baiduIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/$' | '/api/rpc/$' | '/maf/' | '/up_baidu/'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/$' | '/' | '/api/rpc/$' | '/maf' | '/up_baidu'
  id:
    | '__root__'
    | '/_layout'
    | '/api/$'
    | '/_layout/'
    | '/api/rpc/$'
    | '/_layout/maf/'
    | '/_layout/up_baidu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/up_baidu/': {
      id: '/_layout/up_baidu/'
      path: '/up_baidu'
      fullPath: '/up_baidu/'
      preLoaderRoute: typeof LayoutUp_baiduIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/maf/': {
      id: '/_layout/maf/'
      path: '/maf'
      fullPath: '/maf/'
      preLoaderRoute: typeof LayoutMafIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutMafIndexRoute: typeof LayoutMafIndexRoute
  LayoutUp_baiduIndexRoute: typeof LayoutUp_baiduIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutMafIndexRoute: LayoutMafIndexRoute,
  LayoutUp_baiduIndexRoute: LayoutUp_baiduIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
